# -*- coding: utf-8 -*-
"""SI_HW6_Q6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Vz0rOXlwEz_MKrjgKmg-0dFNm1hXXzF
"""

import scipy.stats as stats

# Assuming you have your data in the following format
lemon = [11, 10, 12]
floral = [11, 14, 11]
fried_food = [5, 5, 8]
none = [8, 7, 6]

# Perform one-way ANOVA
f_value, p_value = stats.f_oneway(lemon, floral, fried_food, none)

print("F-value: ", f_value)
print("P-value: ", p_value)

import numpy as np
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# Combine all groups into a single data array
data = np.concatenate([lemon, floral, fried_food, none])

# Create a list of group labels
labels = ['lemon'] * len(lemon) + ['floral'] * len(floral) + ['fried_food'] * len(fried_food) + ['none'] * len(none)

# Perform Tukey's test
tukey_results = pairwise_tukeyhsd(data, labels, 0.05)

# Print the results
print(tukey_results)